## Student Requests

### Create a student
POST http://localhost:8080/api/students
Content-Type: application/json

{
  "nationalId": "12345678",
  "firstName": "Juan",
  "lastName": "Perez",
  "dob": "2005-03-10",
  "email": "juan@example.com",
  "ownPhone": "1122334455",
  "otherPhone": "",
  "address": {
    "street": "Av. Corrientes",
    "number": 1234,
    "city": "Buenos Aires",
    "zip": 1414,
    "country": "Argentina"
  }
}


> {%
    client.global.set("studentId", response.body.id);
%}

### Get a student by ID
GET http://localhost:8080/api/students/{{studentId}}

### Get all students
GET http://localhost:8080/api/students

### Update Student
PUT http://localhost:8080/api/students/{{studentId}}
Content-Type: application/json

{
  "nationalId": "12345678",
  "firstName": "Juan",
  "middleName": "Manuel",
  "lastName": "Perez",
  "dob": "2005-03-10",
  "email": "juan@example.com",
  "ownPhone": "1122334455",
  "otherPhone": "1122335566",
  "address": {
    "street": "Av. Corrientes",
    "number": 1234,
    "city": "Buenos Aires",
    "zip": 1414,
    "country": "Argentina"
  }
}

### Delete Student (hard delete)
DELETE http://localhost:8080/api/students/{{studentId}}